/**
 * Gera as versoes nativas dos design tokens a partir de tokens.json
 * (fonte da verdade unica), opcionalmente sobrepondo um tema de cores.
 *
 * Uso (a partir da raiz de um projeto):
 *   node ../../shared/design-system/sync-tokens.mjs --css design-system/src/tokens.css
 *   node ../../shared/design-system/sync-tokens.mjs --android app/android/app/src/main/res
 *   node ../../shared/design-system/sync-tokens.mjs --theme ocean          (auto-detecta saidas)
 *   node ../../shared/design-system/sync-tokens.mjs --theme-file ./meu-tema.json --css ...
 *
 * --css <arquivo>        escreve custom properties CSS (light + dark).
 * --android <resDir>     escreve <resDir>/colors.xml e <resDir>/values-night/colors.xml.
 * --theme <nome>         usa themes/<nome>.json para sobrepor as cores.
 * --theme-file <caminho> usa um arquivo de tema local ao projeto.
 * Sem --css/--android: auto-detecta design-system/src/tokens.css e
 * app/android/app/src/main/res a partir do diretorio atual.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

function argValue(name) {
  const index = process.argv.indexOf(`--${name}`);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function loadTokens() {
  const tokens = JSON.parse(fs.readFileSync(path.join(here, 'tokens.json'), 'utf8'));
  const themeArg = argValue('theme');
  const themeFileArg = argValue('theme-file');
  if (themeArg && themeFileArg) {
    console.error('Use --theme OU --theme-file, nao ambos.');
    process.exit(1);
  }
  if (themeArg) {
    const themePath = path.join(here, 'themes', `${themeArg}.json`);
    if (!fs.existsSync(themePath)) {
      const available = fs
        .readdirSync(path.join(here, 'themes'))
        .filter((f) => f.endsWith('.json'))
        .map((f) => f.replace(/\.json$/, ''))
        .join(', ');
      console.error(`Tema nao encontrado: ${themeArg}. Disponiveis: ${available}`);
      process.exit(1);
    }
    return applyTheme(tokens, JSON.parse(fs.readFileSync(themePath, 'utf8')), `themes/${themeArg}.json`);
  }
  if (themeFileArg) {
    if (!fs.existsSync(themeFileArg)) {
      console.error(`Arquivo de tema nao encontrado: ${themeFileArg}`);
      process.exit(1);
    }
    return applyTheme(tokens, JSON.parse(fs.readFileSync(themeFileArg, 'utf8')), themeFileArg);
  }
  return { tokens, themeLabel: 'tokens.json' };
}

function applyTheme(tokens, theme, label) {
  for (const mode of ['light', 'dark']) {
    if (!theme.color?.[mode]) {
      console.error(`Tema invalido: falta color.${mode} em ${label}`);
      process.exit(1);
    }
    tokens.color[mode] = { ...tokens.color[mode], ...theme.color[mode] };
  }
  if (theme.name) console.log(`[tokens] theme: ${theme.name} (de ${label})`);
  return { tokens, themeLabel: label };
}

function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function writeIfChanged(file, content) {
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return false;
  fs.writeFileSync(file, content);
  return true;
}

function cssColorBlock(colors) {
  return Object.entries(colors)
    .map(([name, value]) => `  --ds-color-${kebab(name)}: ${value.toLowerCase()};`)
    .join('\n');
}

function cssFor(tokens) {
  const header =
    '/* Generated by shared/design-system/sync-tokens.mjs from tokens.json. Do not edit by hand. */\n';
  return `${header}
:root {
${cssColorBlock(tokens.color.light)}
  --ds-radius-sm: ${tokens.radius.sm};
  --ds-radius-md: ${tokens.radius.md};
  --ds-radius-lg: ${tokens.radius.lg};
  --ds-radius-full: ${tokens.radius.full};
  --ds-shadow-card: ${tokens.shadow.card};
}

@media (prefers-color-scheme: dark) {
  :root {
${cssColorBlock(tokens.color.dark)}
  }
}
`;
}

function androidColors(tokens, mode, { includeLauncher }) {
  const map = {
    primary: 'ds_color_primary',
    primaryHover: null,
    onPrimary: 'ds_color_on_primary',
    surface: 'ds_color_surface',
    background: 'ds_color_background',
    ink: 'ds_color_on_surface',
    muted: 'ds_color_muted',
    border: 'ds_color_border',
    danger: 'ds_color_error',
  };
  const lines = Object.entries(map)
    .filter(([, name]) => name !== null)
    .map(([key, name]) => `    <color name="${name}">${tokens.color[mode][key].toUpperCase()}</color>`);
  if (includeLauncher) {
    lines.push(`    <color name="launcher_background">${tokens.color.light.primary.toUpperCase()}</color>`);
  }
  return `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <!-- Generated from shared/design-system/tokens.json (${mode}). Do not edit by hand. -->\n${lines.join('\n')}\n</resources>\n`;
}

function writeCss(tokens, outPath) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  if (writeIfChanged(outPath, cssFor(tokens))) console.log(`[tokens] wrote ${outPath}`);
  else console.log(`[tokens] ${outPath} already up to date`);
}

function writeAndroid(tokens, resDir) {
  fs.mkdirSync(path.join(resDir, 'values-night'), { recursive: true });
  const light = path.join(resDir, 'colors.xml');
  const dark = path.join(resDir, 'values-night', 'colors.xml');
  if (writeIfChanged(light, androidColors(tokens, 'light', { includeLauncher: true }))) {
    console.log(`[tokens] wrote ${light}`);
  }
  if (writeIfChanged(dark, androidColors(tokens, 'dark', { includeLauncher: false }))) {
    console.log(`[tokens] wrote ${dark}`);
  }
}

const { tokens } = loadTokens();
let cssOut = argValue('css');
let androidOut = argValue('android');

// Auto-deteccao: roda na raiz de um projeto template e aplica onde existir.
if (!cssOut && !androidOut) {
  const cssCandidate = path.resolve('design-system/src/tokens.css');
  const androidCandidate = path.resolve('app/android/app/src/main/res');
  const targets = [];
  if (fs.existsSync(path.dirname(cssCandidate))) targets.push(['css', cssCandidate]);
  if (fs.existsSync(androidCandidate)) targets.push(['android', androidCandidate]);
  if (targets.length === 0) {
    console.error(
      'Nenhuma saida encontrada. Rode na raiz de um projeto ou passe --css/--android.\n' +
        'Usage: sync-tokens.mjs [--theme <nome>] [--css <file>] [--android <resDir>]',
    );
    process.exit(1);
  }
  for (const [kind, target] of targets) {
    if (kind === 'css') writeCss(tokens, target);
    else writeAndroid(tokens, target);
  }
} else {
  if (cssOut) writeCss(tokens, path.resolve(cssOut));
  if (androidOut) writeAndroid(tokens, path.resolve(androidOut));
}
